/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedFeriadosRouteImport } from './routes/_authenticated/feriados'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedMeusRegistrosRouteImport } from './routes/_authenticated/meus-registros'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedRegistrosRouteImport } from './routes/_authenticated/registros'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout/retorno'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeriadosRoute = AuthenticatedFeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusRegistrosRoute =
  AuthenticatedMeusRegistrosRouteImport.update({
    id: '/meus-registros',
    path: '/meus-registros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrosRoute = AuthenticatedRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/checkout/retorno',
  path: '/checkout/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/feriados': typeof AuthenticatedFeriadosRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/meus-registros': typeof AuthenticatedMeusRegistrosRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/feriados': typeof AuthenticatedFeriadosRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/meus-registros': typeof AuthenticatedMeusRegistrosRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/feriados': typeof AuthenticatedFeriadosRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/meus-registros': typeof AuthenticatedMeusRegistrosRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/registros': typeof AuthenticatedRegistrosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planos'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/assinaturas'
    | '/auditoria'
    | '/configuracoes'
    | '/dashboard'
    | '/fechamento'
    | '/feriados'
    | '/funcionarios'
    | '/meus-registros'
    | '/ponto'
    | '/registros'
    | '/relatorios'
    | '/checkout/retorno'
    | '/api/public/cakto-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planos'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/assinaturas'
    | '/auditoria'
    | '/configuracoes'
    | '/dashboard'
    | '/fechamento'
    | '/feriados'
    | '/funcionarios'
    | '/meus-registros'
    | '/ponto'
    | '/registros'
    | '/relatorios'
    | '/checkout/retorno'
    | '/api/public/cakto-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planos'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/_authenticated/assinaturas'
    | '/_authenticated/auditoria'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fechamento'
    | '/_authenticated/feriados'
    | '/_authenticated/funcionarios'
    | '/_authenticated/meus-registros'
    | '/_authenticated/ponto'
    | '/_authenticated/registros'
    | '/_authenticated/relatorios'
    | '/checkout/retorno'
    | '/api/public/cakto-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanosRoute: typeof PlanosRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feriados': {
      id: '/_authenticated/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof AuthenticatedFeriadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-registros': {
      id: '/_authenticated/meus-registros'
      path: '/meus-registros'
      fullPath: '/meus-registros'
      preLoaderRoute: typeof AuthenticatedMeusRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registros': {
      id: '/_authenticated/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AuthenticatedRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/checkout/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedFeriadosRoute: typeof AuthenticatedFeriadosRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedMeusRegistrosRoute: typeof AuthenticatedMeusRegistrosRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedRegistrosRoute: typeof AuthenticatedRegistrosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedFeriadosRoute: AuthenticatedFeriadosRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedMeusRegistrosRoute: AuthenticatedMeusRegistrosRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedRegistrosRoute: AuthenticatedRegistrosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanosRoute: PlanosRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  CheckoutRetornoRoute: CheckoutRetornoRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
